### ISSUE TITLE
Agregar warning de lenguaje adulto

### ISSUE THREAD

**Issue by rolivencia** [rolivencia/cuentoneta#208]
# Descripción
* Ver ejemplo disponible para historias de https://short-stories.co, por ejemplo: https://short-stories.co/stories/the-metro-EWAno9OY5VD

**Comment by SoleSasia** [comment]
@rolivencia La idea seria agregar un campo `warning` (opcional) al schema `story`? Similar a lo que hiciste con el campo `videoUrl`?

**Comment by SoleSasia** [comment]
Lo tomo, pues. :)
