### ISSUE TITLE
Establecer Vite como default para dev server

### ISSUE THREAD

**Issue by rolivencia** [rolivencia/cuentoneta#211]
# Descripción

A partir de Angular 16 existe soporte para correr el dev server utilizando Vite. Migrar a Vite para que sea la herramienta por defecto para ejecutar los dev servers. 

Evaluar cómo poder importar los estilos de Tailwind, los estilos de theme y otros en `styles.scss`, lo cual al momento da error al intentar correr el build. Es probable que el tema tenga que ver con la expresión de las rutas:

Probar cambiar rutas desde `'src/assets/scss/reset'` a `'assets/scss/reset'`, por ejemplo.

**Comment by ErikGIovani** [comment]
Hola 👋
