### ISSUE TITLE
Agregar webhook de github al canal de Discord de La Cuentoneta

### ISSUE THREAD

**Issue by ErikGIovani** [rolivencia/cuentoneta#226]
## Descripción

Solo deben de aparecer las pull request y las issues creadas.

**Comment by rolivencia** [comment]
El webhook fue agregado y está funcional. Sólo resta probarlo @ErikGIovani

**Comment by ErikGIovani** [comment]
> El webhook fue agregado y está funcional. Sólo resta probarlo @ErikGIovani

Genial 👍
