### ISSUE TITLE
Mejorar el performance de la carga de las fonts

### ISSUE THREAD

**Issue by ErikGIovani** [rolivencia/cuentoneta#233]
Agregar la propiedad preconnect a las meta tags para optimizar la carga de las fuentes.

Cambiar la sintaxis de la llamada de las fonts por la nueva versión del api, para en una sola llamada descargar ambas.

**Comment by rolivencia** [comment]
¿Estamos dentro de las posibilidades de hacer esto rápido para incluirlo en la https://github.com/rolivencia/cuentoneta/milestone/3?
