### ISSUE TITLE
Desplegar Storybook en Vercel

### ISSUE THREAD

**Issue by rolivencia** [rolivencia/cuentoneta#234]
# Descripción
Se requiere poner a disposición del equipo de diseño y de desarrollo una instancia de Storybook en un proyecto adicional de Vercel, agregando además la URL del despliegue en el README.md.

**Comment by LPRegen** [comment]
Hola @rolivencia , me gustaría tomar este issue.

**Comment by rolivencia** [comment]
Adelante @LPRegen. Cualquier duda que surja me avisas 🚀

**Comment by LPRegen** [comment]
Hola @rolivencia 
Preferis que cree un deploy en Vercel con mi cuenta o con la cuenta que estas usando para cuentoneta?

**Comment by rolivencia** [comment]
Va a ser necesario que cree un nuevo proyecto en Vercel, lo asigne al mismo repo, pero despliegue en base al comando de Storybook. Hoy dejo eso listo.

Este issue está relacionado con #227, y una vez que esté el proyecto en una organización dedicada y asignado a un correo @cuentoneta.ar (dominio que ya tenemos funcionando con un correo) va a quedar ligado a otra cuenta que no sea específicamente la mía.
