### ISSUE TITLE
Migrar componentes a standalone components

### ISSUE THREAD

**Issue by ErikGIovani** [rolivencia/cuentoneta#273]
* https://angular.io/guide/standalone-components

**Comment by SoyDiego** [comment]
Chicos, voy con esta. Nunca trabajé con standalone componentes así que quizás sea bueno para aprender un poquito más.

**Comment by ErikGIovani** [comment]
> Chicos, voy con esta. Nunca trabajé con standalone componentes así que quizás sea bueno para aprender un poquito más.

Ya te lo asigné
