### ISSUE TITLE
Mostrar nuevamente skeletons de RRSS al navegar entre stories

### ISSUE THREAD

**Issue by rolivencia** [rolivencia/cuentoneta#274]
# Descripción
Al realizar la primera navegación a la vista de Story, los logos de las Redes Sociales muestran un skeleton circular hasta finalizar la carga de datos. Si se intenta navegar entre stories utilizando la navbar izquierda, los skeletons no vuelven a mostrarse sobre los logos.

Es necesario que los skeletons se superpongan a los logos mientras dura la carga para evitar confundir al usuario respecto de qué historia está compartiendo y evitar que presione los botones antes de que la carga de la historia próxima haya terminado.

**Comment by SoyDiego** [comment]
Chicos, me pongo con este...
