### ISSUE TITLE
Rever colaboradores para release 2.0.3

### ISSUE THREAD

**Issue by rolivencia** [rolivencia/cuentoneta#301]
# Descripción
* Actualizar README.md incluyendo colaboraciones de PRs y contenido.
* Actualizar sección `/about` / Nosotros con nuevos colaboradores.

**Comment by SoyDiego** [comment]
@ErikGIovani podrías asignarle este issue a @JimerSamuel para no confundir y saber que este ya esto ya se está haciendo por favor? (no se porqué no puedo etiquetarlo). Gracias!!

**Comment by ErikGIovani** [comment]
> @ErikGIovani podrías asignarle este issue a @JimerSamuel para no confundir y saber que este ya esto ya se está haciendo por favor?. Gracias!!

Por eso decía lo de dejar un comentario en el issue,  si no comenta, github no deja asignarlo,  solo que ya tenga por lo menos un pull request ese usuario o tenga permisos en el repo 😫

**Comment by JimerSamuel** [comment]
Anotado!

**Comment by SoyDiego** [comment]
> > @ErikGIovani podrías asignarle este issue a @JimerSamuel para no confundir y saber que este ya esto ya se está haciendo por favor?. Gracias!!
> 
> Por eso decía lo de dejar un comentario en el issue, si no comenta, github no deja asignarlo, solo que ya tenga por lo menos un pull request ese usuario o tenga permisos en el repo tired_face

Ah no lo sabía. A mi me pasó que no me salia en la lista cuando ponía @ y su nick pero al dar enviar si lo encontraba. Buenísimo, gracias!!
