### ISSUE TITLE
Corregir los tests unitarios que esten fallando

### ISSUE THREAD

**Issue by SoyDiego** [rolivencia/cuentoneta#307]
# Descripción

Despues de hacer la implementación de pasar todos los componentes a Standalone, fallan algunos de los tests unitarios los cuales habría que corregir.

# Requerimientos

- [ ] Corregir test unitarios.

# Recursos

* https://angular.io/guide/testing-components-basics

* https://this-is-angular.github.io/angular-guides/docs/standalone-apis/testing-a-standalone-component-using-the-angular-testbed

**Comment by rolivencia** [comment]
Tal vez los tests estén fallado por la superposición entre los componentes declarados como standalone y el hecho de que se exportan también en módulos. Ver los comentarios que dejé en #303.

**Comment by rolivencia** [comment]
@ErikGIovani, ¿te parece que abramos un nuevo issue para los tests restantes, detallando en una checklist cuáles son los que fallan?

**Comment by ErikGIovani** [comment]
> @ErikGIovani, ¿te parece que abramos un nuevo issue para los tests restantes, detallando en una checklist cuáles son los que fallan?

Me parece perfecto 👌,  si gustas yo lo agrego

**Comment by rolivencia** [comment]
> > @ErikGIovani, ¿te parece que abramos un nuevo issue para los tests restantes, detallando en una checklist cuáles son los que fallan?
> 
> Me parece perfecto 👌, si gustas yo lo agrego

¡Adelante! Recuerda taggearlo para el milestone 2.2
