### ISSUE TITLE
Cambio atributo lang a es

### ISSUE THREAD

**Issue by wilago** [rolivencia/cuentoneta#314]
Realizar el cambio del atributo lang=es 

![image](https://github.com/rolivencia/cuentoneta/assets/27816405/a8a403a5-c47b-4a8e-a5b6-32673902d015)

## Issues relacionados
- #243

**Comment by wilago** [comment]
Hola @rolivencia, lo que me quiere decir es que debo realizar este mismo cambio en la rama  2.0.3?

**Comment by rolivencia** [comment]
No, en absoluto. Tiene que ver con el que este issue ha sido agregado como parte del hito 2.0.3 (que ahora fue renombrada a 2.1.0).

Asignar issues a un hito (milestone) nos permite poder llevar un control de qué issues deben ser priorizados dentro de una ventana de tiempo determinada.

Aquí está la lista de issues del hito en el cual ahora estamos trabajando: https://github.com/rolivencia/cuentoneta/milestone/3
