### ISSUE TITLE
Actualizar a Angular 16.1

### ISSUE THREAD

**Issue by rolivencia** [rolivencia/cuentoneta#319]
# Descripción
Se requiere actualizar, vía Nx, a Angular y sus dependencias core a la versión 16.1.#314 

Las novedades que trae la versión 16.1 pueden leerse en https://blog.ninja-squad.com/2023/06/14/what-is-new-angular-16.1/

Para actualizar Angular a la versión 16.1, se requiere previamente actualizar Nx a la versión 16.4.

## Cómo proceder
Puede visualizarse información sobre cómo actualizar Angular bajo repos basados en Nx en este link: https://nx.dev/more-concepts/nx-and-angular

**Comment by rolivencia** [comment]
Luego de este update podemos intentar nuevamente ir a por el uso de Vite y cerrar el issue #211 @ErikGIovani

**Comment by ErikGIovani** [comment]
> Luego de este update podemos intentar nuevamente ir a por el uso de Vite y cerrar el issue #211 @ErikGIovani 

Genial 👍

**Comment by rolivencia** [comment]
Seguramente la versión con soporte está al caer. Esperemos hasta que esté disponible.

**Comment by rolivencia** [comment]
Salió hoy 22/06 la beta con soporte para Angular 16.1:
https://github.com/nrwl/nx/releases

Supongo la versión estable debe estar al caer.
