### ISSUE TITLE
Transformar StoryComponent y StorylistComponent a standalone

### ISSUE THREAD

**Issue by rolivencia** [rolivencia/cuentoneta#321]
# Descripción

Para poder migrar todos los componentes actualmente en uso en la aplicación a versiones standalone, resta migrar los componentes `StoryComponent` y `StorylistComponent`. 

## Tareas

Los puntos 1, 2 y 4 detallan operaciones ya realizadas para migrar los componentes a standalone. El punto 3 se agrega debido a la naturaleza de componentes _enrutables_ que poseen `StoryComponent` y `StorylistComponent`.

1. Agregar el flag `standalone: true` en el decorator del componente
2. Migrar los imports desde módulos al decorator del componente.
3. En `app-routing.module.ts` se debe cambiar la expresión `loadChildren` en referencia al módulo que abarca al componente por `loadComponent`, cambiando la referencia al mismo.
4. Eliminar los módulos que declaran y exportan el componente.

Más información al respecto: https://www.angulararchitects.io/aktuelles/routing-and-lazy-loading-with-standalone-components/

**Comment by SoyDiego** [comment]
> @SoyDiego Acá está el issue bien formado por si querés seguir con la migración a standalone cubriendo los dos componentes que faltan.

Perfecto, alguno que me la asigne por fa.
