### ISSUE TITLE
Refinamiento de DmcaComponent

### ISSUE THREAD

**Issue by rolivencia** [rolivencia/cuentoneta#346]
### Descripción

# Descripción
Dados los múltiples cambios desde la v1.0 de la plataforma, se hace necesario ajustar el texto de DmcaComponent a la nueva versión de La Cuentoneta.

## Tareas
- [x] El título debe ser ahora "Disclaimer for La Cuentoneta". Todas las referencias a "Cuentos de Verano" deben ser cambiadas a "La Cuentoneta".
- [x] Cambiar correo de contacto a `contacto@cuentoneta.ar`
- [x] Adaptar la sección "Original Sources", la cual debe detallar que cada una de las stories accesibles en nuestro sitio contiene el link original del cual tomamos el material, el cual será visible en la vista `/story` una vez implementado el issue #276. Pedir ayuda a @rolivencia para la redacción del texto si es necesario.
- [x] Remover el listado de stories del contenido (sección Stories List). Esto también incluye deshacerse de la propiedad `linksList` y de la interface `OriginalLink`, ambas agregadas en `DmcaComponent`.
- [x] Agrega la navegación a la sección DMCA en `FooterComponent`.

## Sugerencias
- [x] Dado que no hay demasiadas cosas a implementar a nivel componente, se sugiere transformar la template en inline e incluirla dentro de `DmcaComponent`, en vez de en un archivo HTML separado.

**Comment by rolivencia** [comment]
@SoleSasia acá te dejo el nuevo issue para continuar con el trabajo.

**Comment by SoleSasia** [comment]
@rolivencia: en el titulo, 'La Cuentoneta' deberia ir entre etiquetas <em> o no es necesario?

**Comment by SoleSasia** [comment]
En cuanto a la navegación en el footer, que texto coloco?

![Captura de pantalla de 2023-06-29 11-42-44](https://github.com/rolivencia/cuentoneta/assets/101983696/856f1370-37e6-4c8b-8cf0-be534d451270)

**Comment by SoleSasia** [comment]
En el cuarto párrafo de la sección 'Disclaimers for La Cuentoneta' se hace mención a Cuentos de Verano. Esto se mantiene?

**Comment by rolivencia** [comment]
> En cuanto a la navegación en el footer, que texto coloco?
> 
> ![Captura de pantalla de 2023-06-29 11-42-44](https://user-images.githubusercontent.com/101983696/249805838-856f1370-37e6-4c8b-8cf0-be534d451270.png)

El texto debería ser DMCA. Así está bien.

**Comment by rolivencia** [comment]
> En el cuarto párrafo de la sección 'Disclaimers for La Cuentoneta' se hace mención a Cuentos de Verano. Esto se mantiene?

Buen punto. Todo lo que haga referencia a "Cuentos de Verano" debe ser reemplazado por "La Cuentoneta". Originalmente ese era el nombre de la v1.0 y la app se llamaba "La Cuentoneta". Es por eso que se leen referencias a ambas cosas.

**Comment by rolivencia** [comment]
> @rolivencia: en el titulo, 'La Cuentoneta' deberia ir entre etiquetas < em > o no es necesario?

No es necesario. Como ejemplo fijate el estilo de "Nosotros" (en el componente `AboutComponent`. Lamentablemente no tenemos diseños en Figma para esta parte, así que improvisemos en el camino pero manteniendo la consistencia.

**Comment by SoleSasia** [comment]
> ## Sugerencias
> * [ ]  Dado que no hay demasiadas cosas a implementar a nivel componente, se sugiere transformar la template en inline e incluirla dentro de `DmcaComponent`, en vez de en un archivo HTML separado.

@rolivencia, los estilos de este componente son los mismos que `AboutComponent`. Seguirá siendo un archivo separado hasta que se resuelva el issue [#263 Componente para proyectar contenido...](https://github.com/rolivencia/cuentoneta/issues/263) , verdad?

**Comment by rolivencia** [comment]
> > ## Sugerencias
> > 
> > * [ ]   Dado que no hay demasiadas cosas a implementar a nivel componente, se sugiere transformar la template en inline e incluirla dentro de `DmcaComponent`, en vez de en un archivo HTML separado.
> 
> @rolivencia, los estilos de este componente son los mismos que `AboutComponent`. Seguirá siendo un archivo separado hasta que se resuelva el issue [#263 Componente para proyectar contenido...](https://github.com/rolivencia/cuentoneta/issues/263) , verdad?

Así es. No te preocupes por los estilos duplicados por el momento, luego lo trabajamos como parte del #263.

**Comment by rolivencia** [comment]
El trabajo de #276 ya está mergeado en la rama `release/2.1`. Lo hecho ahí reemplaza la necesidad de tener la lista de todos los links originales de todas las stories incluidas en la plataforma en el `DmcaComponent`.
