### ISSUE TITLE
Corregir los test

### ISSUE THREAD

**Issue by ErikGIovani** [rolivencia/cuentoneta#358]
### Descripción

Corregir los tests faltantes para que pasen las pruebas y cada test se debe de hacer como un issue independiente.

### Test por Corregir: 

- [x] #367
- [x] #378
- [x] meta-tags.directive.spec.ts
- [x] home.component.spec.ts
- [x] dmca.component.spec.ts
- [x] story.component.spec.ts
- [x] storylist.component.spec.ts
- [x] content.service.spec.ts
- [x] storylist.service.spec.ts

### Criterios de aceptación

Al correr los test asegurarse que el archivo de testing recién corregido pase las pruebas.

### Recursos

* [Testing de Directivas](https://angular.io/guide/testing-attribute-directives)
* [Testing de Servicios](https://angular.io/guide/testing-services)
* [Testing de Componentes](https://testing-library.com/docs/angular-testing-library/examples)

**Comment by gustavoPetruzzi** [comment]
Gente, si quieren tomo los tests del tooltip.directive
