### ISSUE TITLE
Agregar soporte para cuentos en formato video

### ISSUE THREAD

**Issue by rolivencia** [rolivencia/cuentoneta#359]
### Descripción

Se requiere poder visualizar como parte de la vista de lectura de stories un video embebido, cuyo añadido será opcional para cada story, y representará una versión recitada o leída del cuento disponible en plataformas como YouTube, Vimeo, Dailymotion, etc.

## Tareas
- [x] Agregar la propiedad `videoUrl` al schema `story` de Sanity
- [ ] Agregar la propiedad `videoUrl`, de tipo `string`, al modelo `StoryBase` en `story.model.ts`. La propiedad debe ser opcional.
- [ ] Implementar el tag `<iframe>` dentro de `StoryComponent` para poder visualizar. Ver comentario relacionado al feature para videos de YouTube.
- [ ] Modificar la UI/UX de la vista story para visualizar cómo implementar el video embebido en la vista story.
- [ ] Modificar la UI/UX de la navbar izquierda para indicar que la storylist posee un video disponible.
- [ ] Modificar la UI/UX del componente `StoryCardComponent` para incluir un ícono, con un tooltip asociado, que permita hacer saber al usuario respecto de la existencia de contenido en video para una story determinada.
- [ ] Llevar adelante una sesión de revisión del código relevante a este feature para un refactor y _emprolijamiento_ del código.

### Criterios de aceptación

* Al acceder a la vista de lectura de story, con una Story que posea un `videoUrl` definido, debe visualizarse una ventana embebida desde la cual nuestro usuario puede reproducir el video asociado a la story.
* Al visualizarse una instancia de `StoryCardComponent`, nuestro usuario debe ser capaz de visualizar un ícono, con un tooltip que aparezca al hacer hover/tap/click sobre él, que ayude a explicitar que una determinada story posee un video embebido asociado.

### Recursos

* [Mockups y diseños en Figma](https://www.figma.com/file/BIlQ6U3eh3M8vtYQt3vLNW/La-Cuentoneta-v2)

**Comment by SoleSasia** [comment]
Ni bien consiga correr el proyecto puedo intentar resolver esto :D

**Comment by rolivencia** [comment]
Un cuento ya cargado para hacer una prueba: "La Máscara de la Muerte Roja", de Edgar Allan Poe, disponible en la storylist "La Cuentoneta 1.0.

- Acceso en producción: https://www.cuentoneta.ar/story?slug=la-mascara-de-la-muerte-roja&list=verano-2022
- Link local: http://localhost:4200/story?slug=la-mascara-de-la-muerte-roja&list=verano-2022

Video de Laiseca recitando el cuento: https://www.youtube.com/watch?v=ksq2a1ucEIs

**Comment by SoleSasia** [comment]
> Código de ejemplo para embeber un video de YouTube, usando el link adjunto:
> 
> ```
> <iframe width="560" height="315" src="https://www.youtube.com/embed/ksq2a1ucEIs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
> ```

@rolivencia, consegui implementar el tag <iframe> con el código de ejemplo. Sólo que al usar binding en el atributo `src` salta un error de securidad:

![Captura de pantalla de 2023-07-21 15-31-28](https://github.com/rolivencia/cuentoneta/assets/101983696/c03915ac-5bd7-478e-8d97-387b4a4973f4)

Por lo que vi, las url deberian ser estáticas. Y al ser dinámicas hay algo ahí con el sanitizador que no funciona.

**Comment by SoleSasia** [comment]
@rolivencia, implementé la sanitización a lo tradicional, digamos... Todavía no entiendo bien la prog funcional.

Vas a ver que en el `story.component.ts` dejé un código comentado: eso me daba error por tener `videoUrl` undefined, y no renderizaba ninguna story.

Ahora renderiza el video pero super lento...

Spongo que se podrá mejorar en estos días.
