### ISSUE TITLE
Transformar AppComponent en standalone

### ISSUE THREAD

**Issue by rolivencia** [rolivencia/cuentoneta#360]
### Descripción

Como parte de la migración de todos nuestros componentes al formato standalone, se hace necesario también migrar `AppComponent`, el componente principal de la aplicación.

Debe tenerse precaución al tomar este issue, debido a que hay aspectos arquitecturales importantes de la aplicación que serán modificados.

### Criterios de aceptación

* `AppComponent` transformado en componente standalone, con toda la funcionalidad antes en el `AppModule` ahora disponible en el `AppComponent` y un archivo de routes 
* `AppModule` eliminado.

**Comment by SoyDiego** [comment]
Voy con este ^^

**Comment by rolivencia** [comment]
Dejo por acá un proyecto vacío, de ejemplo, con `AppComponent` en modo standalone

**Comment by SoyDiego** [comment]
> 

Genial, mañana me lo miro! 
Gracias!
