### ISSUE TITLE
Corregir Link en  Contributing.md

### ISSUE THREAD

**Issue by yamilt351** [rolivencia/cuentoneta#392]
### ¿Existe un problema similar reportado?

- [ ] Existe un problema similar
- [ ] Es un problema completamente nuevo

### Descripción del problema

La Documentacion de contribucion tiene un error en el md 

### Pasos para reproducir el problema

- ir a [contributing.md](https://github.com/rolivencia/cuentoneta/blob/develop/CONTRIBUTING.md)
- seccion Contribuyendo código

### Comportamiento esperado

se deberia renderizar un link para redigirir al usuario a la guia de contribuciones

### Capturas de pantalla

![image](https://github.com/rolivencia/cuentoneta/assets/88646148/f87dbacd-00d4-4933-8713-49b06a53354f)

### Información adicional / Recursos

- Nose que link se deberia renderizar ahi

**Comment by rolivencia** [comment]
Si querés subite un PR para corregirlo @yamilt351

**Comment by yamilt351** [comment]
cuando lo habia 'corregido' en mi local, el link no funcionaba, Nose a que parte deberia ir ese link por eso no subi un pr
